<?php
/**
 * @file
 * Code for the GSB Feature School Story Content Type feature.
 */

include_once 'gsb_feature_school_story_ct.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for school story node edit form.
 */
function gsb_feature_school_story_ct_form_school_story_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'school_story_node_form') {
    return;
  }

  $language = $form['language']['#value'];

  $form['field_link_key_audio']['#states'] = array(
    'visible' => array(
      ':input[name="field_icon[' . $language . ']"]' => array(
        array('value' => 'audio'),
      ),
    ),
  );

  $form['field_link_key_video']['#states'] = array(
    'visible' => array(
      ':input[name="field_icon[' . $language . ']"]' => array(
        array('value' => 'video'),
      ),
    ),
  );

  // Hide alumni fields if the alumni checkbox is not checked.
  $form['field_program_single']['#states']['invisible'][':input[name="field_alumni_story[' . $language . ']"]'] = array(
    array('checked' => FALSE),
  );
}

/**
 * Implements hook_ds_pre_render_alter()
 *
 * Determine if the related section has any items.
 * If it doesn't, then we will remove it so that they do not render as empty section.
 */
function gsb_feature_school_story_ct_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {

  // if the context is an idea story, and the view mode is full
  if (!empty($context['bundle']) && $context['bundle'] == 'school_story' && $context['view_mode'] == 'full') {

    // get the id for the related section in the right-hand layout
    $related_id = -1;
    foreach($layout_render_array['right'] as $key => $right_stuff) {
      if (!empty($right_stuff['#id'])) {
        $related_id = $key;
      }
    }

    if ($related_id != -1) {
      $related_faculty = array();
      if (!empty($context['entity']->field_related_faculty)) {
        $item_id = $context['entity']->field_related_faculty['und'][0]['value'];
        $related_faculty = $layout_render_array['right'][$related_id]['field_related_faculty'][0]['entity']['field_collection_item'][$item_id]['#entity']->field_person_fac_single_ref;
      }
      $publication = array();
      if (!empty($context['entity']->field_related_other_unlimited)) {
        $item_id = $context['entity']->field_related_other_unlimited['und'][0]['value'];
        $publication = $layout_render_array['right'][$related_id]['field_related_other_unlimited'][0]['entity']['field_collection_item'][$item_id]['#entity']->field_related_other_content;
      }
      $idea_story = array();
      if (!empty($layout_render_array['right'][$related_id]['field_related_idea_story'])) {
        $idea_story = $layout_render_array['right'][$related_id]['field_related_idea_story'];
      }
      $links = array();
      if (!empty($layout_render_array['right'][$related_id]['field_link_unlimited'])) {
        $links = $layout_render_array['right'][$related_id]['field_link_unlimited'];
      }      
      // remove the related section if there are no items
      if(empty($related_faculty) && empty($publication) && empty($idea_story) && empty($links)) {
        unset($layout_render_array['right'][$related_id]);
      }
    }

  }

}

/**
 * Implements hook_field_extra_fields().
 */
function gsb_feature_school_story_ct_field_extra_fields() {

  $extra['node']['school_story']['display']['gsb_featured_links'] = array(
    'label' => t('Featured Links'),
    'description' => t('Featured Links.'),
    'weight' => 30,
  );

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_feature_school_story_ct_node_view($node, $view_mode, $langcode) {
  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);
  if (empty($fields['gsb_featured_links']['visible'])) {
    return;
  }

  $entity_type = 'fieldable_panels_pane';
  $entity_id = '12006';
  $entity = entity_load_single($entity_type, $entity_id);
  $render_array = entity_view($entity_type, array($entity_id => $entity));
  $content = render($render_array);

  $node->content['gsb_featured_links'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'featured-links',
      ),
    ),
    '#children' => $content,
  );
}

